#!/usr/bin/env python3
"""
qwen_slide_designer.py

Second-stage Qwen module for BollywoodKoko.

Pipeline:
    qwen_converter.py
        ↓
    slide_001.json ... slide_00n.json
        ↓
    qwen_slide_designer.py
        ↓
    slide_001.json ... slide_00n.json
        + "design" section generated by Qwen3:8b
        ↓
    paint_slides.py

This module does NOT paint pixels. It uses Qwen to act as a
"creative director" and generates a structured visual design brief
which the renderer can execute deterministically.

Example:
    python qwen_slide_designer.py

Only news:
    python qwen_slide_designer.py --category news

Output is written back into the same slide JSON files by default.
Use --output-root if you want a separate directory.
"""

import argparse
import json
import re
import sys
from pathlib import Path

import requests


DEFAULT_INPUT = "../OP_JSON/qwen_input"
DEFAULT_OUTPUT = None

DEFAULT_OLLAMA_URL = "http://localhost:11434"
DEFAULT_MODEL = "qwen3:8b"
DEFAULT_TEMPERATURE = 0.2
DEFAULT_TIMEOUT = 120


# ---------------------------------------------------------------------------
# TEXT / JSON HELPERS
# ---------------------------------------------------------------------------

def clean_text(value):
    if value is None:
        return ""
    return re.sub(r"\s+", " ", str(value)).strip()


def strip_thinking(text):
    """Remove Qwen3 reasoning output before JSON parsing."""
    if not text:
        return ""

    text = re.sub(
        r"<think>.*?</think>",
        "",
        text,
        flags=re.DOTALL | re.IGNORECASE,
    )

    return text.strip()


def strip_json_fence(text):
    text = text.strip()

    match = re.match(
        r"^```(?:json)?\s*(.*?)\s*```$",
        text,
        flags=re.DOTALL | re.IGNORECASE,
    )

    return match.group(1).strip() if match else text


def parse_json(raw):
    text = strip_json_fence(strip_thinking(raw))

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        start = text.find("{")
        end = text.rfind("}")

        if start >= 0 and end > start:
            return json.loads(text[start:end + 1])

        raise


# ---------------------------------------------------------------------------
# OLLAMA
# ---------------------------------------------------------------------------

def check_ollama(url):
    try:
        response = requests.get(
            url.rstrip("/") + "/api/tags",
            timeout=10,
        )
        response.raise_for_status()
        return True
    except requests.RequestException as exc:
        print(f"[ERROR] Ollama is not reachable: {exc}")
        return False


def design_slide(
    slide,
    source,
    ollama_url,
    model,
    temperature,
    timeout,
):
    """
    Ask Qwen to classify the story and produce a renderer-friendly
    visual specification.
    """

    headline = clean_text(slide.get("headline"))
    story = clean_text(slide.get("story"))
    category = clean_text(slide.get("category"))
    category_label = clean_text(slide.get("category_label"))
    image_url = clean_text(slide.get("image_url"))

    source_title = clean_text(source.get("title"))
    source_description = clean_text(source.get("description"))

    prompt = f"""
You are the creative director for a premium Bollywood entertainment
news Instagram account.

Your task is NOT to write the news article.
Your task is to decide HOW this particular news story should be
presented visually on ONE Instagram carousel slide.

The final renderer will be HTML/CSS or Pillow, so you must return a
precise structured design specification.

========================
STORY INFORMATION
========================

CATEGORY:
{category_label or category}

HEADLINE:
{headline}

ENGLISH STORY:
{story}

ORIGINAL SOURCE TITLE:
{source_title}

SOURCE ARTICLE:
{source_description}

IMAGE URL:
{image_url}

========================
YOUR OBJECTIVE
========================

Identify the SINGLE strongest news angle.

Ask yourself:

"What should a person notice in the first 1-2 seconds?"

Examples:
- A streaming record → make the number the hero.
- A box-office story → make collection/record the hero.
- A new movie announcement → make the movie/title the hero.
- A casting announcement → make the actor + project the hero.
- A release date → make the date the hero.
- A trailer/teaser → make the film/show title the hero.
- An award → make the award/achievement the hero.
- Celebrity news → make the person + development the hero.

Do not treat every word of the article equally.

========================
LAYOUT TYPES
========================

Choose exactly ONE:

hero_stat
hero_title
split_story
portrait_focus
announcement
release_date
award
streaming_record
box_office
quote_focus
comparison
standard_news

Choose the most appropriate type based ONLY on the supplied story.

========================
OUTPUT
========================

Return ONLY valid JSON with exactly these keys:

{{
  "layout": "string",
  "story_type": "string",
  "visual_priority": "string",
  "hero_text": "string",
  "hero_label": "string",
  "secondary_text": "string",
  "secondary_label": "string",
  "supporting_text": "string",
  "emphasis_words": [],
  "image_treatment": "string",
  "image_position": "string",
  "text_position": "string",
  "headline_style": "string",
  "story_style": "string",
  "show_story": true,
  "show_date": true,
  "show_source_brand": true,
  "design_notes": "string"
}}

========================
RULES
========================

1. FACTUALITY
- Use ONLY facts present in the supplied story/source.
- Never invent numbers, dates, quotes, achievements or context.
- Never infer facts from the image URL.
- If a statistic is present, preserve it accurately.

2. HERO TEXT
- "hero_text" should contain the most visually important short piece
  of information.
- It may be a number, title, person's name, date or short phrase.
- Keep it SHORT.
- Prefer 1-5 words.
- Do not put the whole article into hero_text.

3. HERO LABEL
- Explain the hero value in 1-5 words.
- Example: "VIEWS IN WEEK 2"
- Example: "GLOBAL RANK"
- Example: "RELEASE DATE"

4. SECONDARY TEXT
- Use a second important fact only if one exists.
- Otherwise return an empty string.

5. SUPPORTING TEXT
- One short supporting statement.
- It should complement the hero rather than repeat it.
- Do not copy the full story.

6. EMPHASIS WORDS
- Return 1-4 exact words/phrases from the headline/story.
- These are words the renderer may highlight.
- Do not invent wording.
- Preserve movie/show/person names exactly as supplied.

7. IMAGE
Choose:
- "full_bleed"
- "portrait_crop"
- "top_focus"
- "bottom_focus"
- "side_crop"
- "darkened_full_bleed"

For image_position choose:
- "center"
- "top"
- "bottom"
- "left"
- "right"

Do NOT claim that a person is visible in the image unless the source
information establishes it. The renderer only knows the image URL.

8. TEXT POSITION
Choose:
- "top"
- "center"
- "lower_third"
- "bottom"
- "left"
- "right"

9. HEADLINE STYLE
Choose a concise descriptor such as:
- "large_bold"
- "large_compact"
- "medium_bold"
- "stacked"
- "hero_number"
- "hero_title"

10. STORY STYLE
Choose:
- "compact"
- "three_lines"
- "short_paragraph"
- "minimal"
- "hidden"

11. show_story
Set false when the visual concept is strong enough that the hero
and supporting text communicate the news without the full story.
Set true when additional context is important.

12. show_date
Normally true.

13. show_source_brand
Always true.

14. DESIGN NOTES
Give short implementation guidance for the renderer.
Do NOT describe imaginary visual elements that are not supported
by the available information.

15. LANGUAGE
All design metadata must be in English.

16. PROPER NAMES
Never translate or transliterate:
- movie names
- series names
- show names
- song names
- episode names
- character names
- actor names
- platform names
- company names
- brands

Use the exact English wording supplied by the source.

========================
FINAL CHECK
========================

Before returning JSON, silently verify:
- exactly one layout
- no invented facts
- hero_text is short
- all statistics are accurate
- proper names remain unchanged
- JSON is valid
- no Markdown
- no explanation outside JSON

RETURN JSON ONLY.
"""

    response = requests.post(
        ollama_url.rstrip("/") + "/api/generate",
        json={
            "model": model,
            "prompt": prompt,
            "stream": False,
            "format": "json",
            "options": {
                "temperature": temperature,
            },
        },
        timeout=timeout,
    )

    response.raise_for_status()

    result = response.json()
    raw = result.get("response", "")

    if not raw:
        raise ValueError("Ollama returned an empty response.")

    design = parse_json(raw)

    # Keep only the fields expected by the renderer.
    allowed = {
        "layout",
        "story_type",
        "visual_priority",
        "hero_text",
        "hero_label",
        "secondary_text",
        "secondary_label",
        "supporting_text",
        "emphasis_words",
        "image_treatment",
        "image_position",
        "text_position",
        "headline_style",
        "story_style",
        "show_story",
        "show_date",
        "show_source_brand",
        "design_notes",
    }

    design = {
        key: design.get(key)
        for key in allowed
    }

    if not isinstance(design.get("emphasis_words"), list):
        design["emphasis_words"] = []

    return design


# ---------------------------------------------------------------------------
# PROCESSING
# ---------------------------------------------------------------------------

def process_file(
    json_path,
    output_path,
    ollama_url,
    model,
    temperature,
    timeout,
):
    with json_path.open("r", encoding="utf-8") as f:
        data = json.load(f)

    slide = data.get("slide", {})
    source = data.get("source", {})

    number = slide.get("number", json_path.stem)

    print(f"  [{number}] {slide.get('headline', '')[:90]}")

    design = design_slide(
        slide=slide,
        source=source,
        ollama_url=ollama_url,
        model=model,
        temperature=temperature,
        timeout=timeout,
    )

    # Preserve existing JSON and append/update only the design section.
    data["design"] = {
        "generated_by": "qwen",
        "model": model,
        "version": "1.0",
        **design,
    }

    output_path.parent.mkdir(parents=True, exist_ok=True)

    with output_path.open("w", encoding="utf-8") as f:
        json.dump(
            data,
            f,
            ensure_ascii=False,
            indent=2,
        )


def main():
    parser = argparse.ArgumentParser(
        description="Use local Qwen3:8b as a creative director for carousel slides."
    )

    parser.add_argument(
        "--input",
        default=DEFAULT_INPUT,
        help="Root directory containing category/slide_*.json",
    )

    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=(
            "Output root. Default is the same as --input, so existing "
            "slide JSON files are updated in place."
        ),
    )

    parser.add_argument(
        "--ollama-url",
        default=DEFAULT_OLLAMA_URL,
    )

    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
    )

    parser.add_argument(
        "--temperature",
        type=float,
        default=DEFAULT_TEMPERATURE,
    )

    parser.add_argument(
        "--timeout",
        type=int,
        default=DEFAULT_TIMEOUT,
    )

    parser.add_argument(
        "--category",
        default=None,
        help="Process only one category, e.g. news.",
    )

    parser.add_argument(
        "--force",
        action="store_true",
        help="Regenerate design even if a design section already exists.",
    )

    args = parser.parse_args()

    input_root = Path(args.input)
    output_root = Path(args.output) if args.output else input_root

    if not input_root.exists():
        print(f"[ERROR] Input directory not found: {input_root}")
        sys.exit(1)

    print("=" * 70)
    print("BollywoodKoko Qwen Slide Designer")
    print("=" * 70)
    print(f"Input   : {input_root}")
    print(f"Output  : {output_root}")
    print(f"Ollama  : {args.ollama_url}")
    print(f"Model   : {args.model}")
    print()

    if not check_ollama(args.ollama_url):
        sys.exit(1)

    if args.category:
        category_dirs = [input_root / args.category]
    else:
        category_dirs = sorted(
            p for p in input_root.iterdir()
            if p.is_dir()
        )

    processed = 0
    skipped = 0
    failed = 0

    for category_dir in category_dirs:
        if not category_dir.exists():
            print(f"[WARN] Category not found: {category_dir}")
            continue

        files = sorted(category_dir.glob("slide_*.json"))

        if not files:
            continue

        print("=" * 70)
        print(f"Category: {category_dir.name} ({len(files)} slides)")
        print("=" * 70)

        for json_path in files:
            relative = json_path.relative_to(input_root)
            output_path = output_root / relative

            try:
                if not args.force:
                    with json_path.open("r", encoding="utf-8") as f:
                        existing = json.load(f)

                    if existing.get("design"):
                        print(
                            f"  [SKIP] {json_path.name} already has design "
                            f"(use --force to regenerate)"
                        )
                        skipped += 1
                        continue

                process_file(
                    json_path=json_path,
                    output_path=output_path,
                    ollama_url=args.ollama_url,
                    model=args.model,
                    temperature=args.temperature,
                    timeout=args.timeout,
                )

                processed += 1

            except Exception as exc:
                print(
                    f"  [ERROR] {json_path.name}: {exc}"
                )
                failed += 1

    print()
    print("=" * 70)
    print("COMPLETE")
    print("=" * 70)
    print(f"Generated : {processed}")
    print(f"Skipped   : {skipped}")
    print(f"Failed    : {failed}")
    print(f"Output    : {output_root}")


if __name__ == "__main__":
    main()
